import type { Metadata } from 'next'
import Navbar from '@/components/ui/Navbar'
import Footer from '@/components/ui/Footer'
import Rights from '@/components/ui/Rights'

export const metadata: Metadata = {
    title: 'Main',
    description: 'Generated by create next app',
}

export default function MainLayout({children}:{children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className="bg-C6">
                <Navbar />
                    {children}
                {/* <Footer/> */}
                <Rights />
            </body>
        </html>
    )
}